<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-05-27 13:53

$extensionPath = t3lib_extMgm::extPath('seminarspaypal');
return array(
	'tx_seminarspaypal_hooks_myevents' => $extensionPath . 'Hooks/class.tx_seminarspaypal_Hooks_MyEvents.php',
	'tx_seminarspaypal_hooks_myeventstest' => $extensionPath . 'Tests/Hooks/MyEventsTest.php',
);
?>